import Provider from '@/components/common/provider';
import { workSans } from '@/constant/font.constant';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import '@/styles/globals.css';
import '@/styles/animation.css';

export const metadata: Metadata = {
  title: 'Momentus',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          workSans.className,
          'from-neutral-900 tracking-tighter antialiased',
        )}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
