import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import './globals.css';
import Provider from '@/components/common/provider';
import { GeistSans } from 'geist/font/sans';

export const metadata: Metadata = {
  title: 'Momentus',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          GeistSans.className,
          'from-neutral-900 tracking-tight antialiased',
        )}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
